project:
  type: book
  output-dir: docs

book:
  title: "UMN EEB Quant/Comp Repo"
  repo-url: https://github.com/cwojan/umn_eeb_quant_comp_repo
  downloads: [pdf]
  chapters:
    - index.qmd
    - part: "Iteration: Loops, Functions, and the purr package"
      chapters:
        - intro_iteration.qmd
        - loop_types.qmd
        - when_loops.qmd
        - functions.qmd
        - purrr.qmd
        - parallel_computing.qmd
        - vectorization.qmd
    - part: "git, GitHub, Building Websites, and Copilot"
      chapters:
        - git_github.qmd
        - organizing_repositories.qmd
        - building_webpages.qmd
        - copilot.qmd
    - part: Data Pipelines with Google Drive and Google Sheets
      chapters:
        - account_setup.qmd
        - access_files.qmd
        - create_sheets.qmd
        - backup_data.qmd
        - read_sheets.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: flatly
      dark: darkly
  pdf:
    documentclass: scrreprt

editor: visual

