---
title: "Intro to Iteration"
---

This workshop will be focused on **iteration**, or performing the same code numerous times, potentially on some range of values, in R. It assumes that you know most of the basics of R programming.

R has various ways to iterate, including looping, using functions/functionals, and vectorization. We will go over each to some extent, with examples included. A general guideline for iterating is that if you are copying and pasting code multiple times, you may be better served with a loop or a function. We will cover the following:

1.  Loops

    1.  Types of loops: for, while, and repeat

    2.  When to use which types of loops

    3.  Potential downsides of using loops

    4.  When use a loop is still necessary anyway

2.  Functions and Functionals

    1.  How to write functions

    2.  Benefits of functions

    3.  How to iterate functions with the purr package

    4.  How to iterate even faster with parallel computing

3.  Vectorization

    1.  Benefits of vectorization

    2.  Limitations
